### PR TITLE
Support RESTful API module

### PR DESCRIPTION
**Pull request by yurabakhtin**
Issue: https://github.com/humhub/humhub-modules-rest/issues/33

### CODE REVIEW

**Comment by yurabakhtin** [comment]
We still should implement API tests here.

**Review by luke- — APPROVED** [review]

**Review by luke- — CHANGES_REQUESTED** [review]
@yurabakhtin Can you please check following test. https://github.com/humhub/cfiles/runs/2295954027?check_suite_focus=true#step:25:67

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please check following test. https://github.com/humhub/cfiles/runs/2295954027?check_suite_focus=true#step:25:67

I cannot reproduce this.
The error appears on the test:

```php
$I->sendDelete('cfiles/items/container/1/delete', [
    'selection' => ['file_1', 'file_2', 'folder_5', 'folder_4', 'folder_3', 'folder_2'],
]);
```

This is a single `Delete` test where I passed params, all other tests are used without params like `$I->sendDelete('cfiles/items/container/1/delete');` so I could not compare why it doesn't work with params.
Probably issue in the Yii method `Yii::$app->request->post()` because it is used to initalize the `selection` param https://github.com/humhub/cfiles/blob/enh/33-rest-api-module/models/forms/SelectionForm.php#L32-L37:

```php
class SelectionForm extends \yii\base\Model
{
...
    public function init()
    {
        if(Yii::$app->request->post()) {
            $this->selection = Yii::$app->request->post('selection');
        }
    }
...
```

Probably somehow `Yii::$app->request->post()` doesn't work here because the request has the method `DELETE` and not `POST` as we have on normal work from browser request, but currently my `yii\web\Request` has:

```php
public function post($name = null, $defaultValue = null)
{
    if ($name === null) {
        return $this->getBodyParams();
    }

    return $this->getBodyParam($name, $defaultValue);
}
```

So it must works to get params from body.

Do you have any idea what can be wrong, probably we should update some core Yii files for the tests on the test server side?

**Comment by luke-** [comment]
@yurabakhtin On my machine, all tests also run without errors until I run a "composer update" in the HumHub master repo.
Then I get exactly this error.

```
  - Upgrading webmozart/assert (1.9.1 => 1.10.0): Extracting archive
  - Upgrading phpspec/prophecy (1.12.2 => 1.13.0): Extracting archive
  - Upgrading symfony/yaml (v4.4.19 => v4.4.21): Extracting archive
  - Upgrading symfony/finder (v4.4.19 => v4.4.20): Extracting archive
  - Upgrading symfony/event-dispatcher (v4.4.19 => v4.4.20): Extracting archive
  - Upgrading symfony/css-selector (v4.4.19 => v4.4.20): Extracting archive
  - Upgrading psr/container (1.0.0 => 1.1.1): Extracting archive
  - Upgrading symfony/console (v4.4.19 => v4.4.21): Extracting archive
  - Upgrading guzzlehttp/psr7 (1.7.0 => 1.8.1): Extracting archive
  - Upgrading codeception/codeception (4.1.18 => 4.1.20): Extracting archive
  - Upgrading codeception/module-rest (1.2.8 => 1.3.0): Extracting archive
  - Upgrading symfony/process (v4.4.19 => v4.4.20): Extracting archive
  - Upgrading symfony/dom-crawler (v4.4.19 => v4.4.20): Extracting archive
  - Upgrading codeception/lib-innerbrowser (1.4.0 => 1.4.2): Extracting archive
  - Upgrading kartik-v/bootstrap-fileinput (v5.1.4 => v5.1.5): Extracting archive
  - Upgrading kartik-v/yii2-krajee-base (v2.0.5 => v2.0.6): Extracting archive
  - Upgrading kartik-v/yii2-widget-sidenav (v1.0.0 => v1.0.1): Extracting archive
  - Upgrading npm-asset/jquery (3.5.1 => 3.6.0): Extracting archive
  - Upgrading squizlabs/php_codesniffer (3.5.8 => 3.6.0): Extracting archive
  - Upgrading phpoffice/phpspreadsheet (1.16.0 => 1.17.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Upgrading web-token/jwt-core (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading web-token/jwt-checker (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading web-token/jwt-signature (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading web-token/jwt-signature-algorithm-ecdsa (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading web-token/jwt-signature-algorithm-hmac (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading web-token/jwt-signature-algorithm-rsa (v2.2.8 => v2.2.10): Extracting archive
  - Upgrading fakerphp/faker (v1.13.0 => v1.14.1): Extracting archive
  ```

Seems it is probably related to a Codeception update. Can you take a closer look at this?

**Comment by yurabakhtin** [comment]
@luke- Thank you for the info about `composer update`, after this I could reproduce the issue.
Please review my fix https://github.com/humhub/cfiles/pull/111/commits/d7be40fae7614ff6b041d3e643e34212ab06f565.
After debugging I detected the `$I->sendDelete( 'delete/action', ['param' => 'value'] )` sends params as GET params and not BODY params as it is passed by other methods like `$I->sendPut()`, `$I->sendPatch()`.
It seems strange, I think it is handled by `Codeception\Module\REST::QUERY_PARAMS_AWARE_METHODS = ['GET', 'HEAD', 'DELETE', 'OPTIONS'];`.

**Review by luke- — APPROVED** [review]

**Pull request merged**
