### PR TITLE
File listing layout broken

### PR DESCRIPTION
**Pull request by s-tyshchenko**
Issue: https://github.com/humhub/cfiles/issues/152

### CODE REVIEW

**Comment by luke-** [comment]
@s-tyshchenko Did you tested it with the wide enterprise theme?

**Comment by luke-** [comment]
Can you please add some screenshots?

**Comment by s-tyshchenko** [comment]
> Can you please add some screenshots?
### Enterprise Theme

- original size
Снимок экрана 2022-02-16 в 12 02 03

- zoomed:
Снимок экрана 2022-02-16 в 12 03 00

### HumHub Theme

- original size:
Снимок экрана 2022-02-16 в 12 03 50

-zoomed:
Снимок экрана 2022-02-16 в 12 05 03

**Comment by s-tyshchenko** [comment]
> @s-tyshchenko I can't currently recreate it myself. I will report if it occurs again.

For me it does break in all browsers (I tried Safari, Opera, Chrome and Firefox):

Снимок экрана 2022-03-08 в 12 35 36

**Pull request merged**
